name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Update diagram
        id: make_diagram
        # Ik kan niet vinden waar ik de should_push: false in de .yml file moet steken
        # should_push: false
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "my-diagram"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "my-diagram"
          path: "downloads"


